create table if not exists public.products (
  id bigint primary key generated by default as identity,
  name text not null,
  price integer not null check (price >= 0),
  image_position text not null,
  description text not null
);

create table if not exists public.learning_materials (
  id bigint primary key generated by default as identity,
  title text not null,
  duration text not null,
  steps jsonb not null default '[]'::jsonb
);

create table if not exists public.program_budgets (
  id smallint primary key,
  description text not null,
  amount bigint not null check (amount >= 0)
);

alter table public.products enable row level security;
alter table public.learning_materials enable row level security;
alter table public.program_budgets enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
  on public.products for select to anon, authenticated using (true);

drop policy if exists "Public can read learning materials" on public.learning_materials;
create policy "Public can read learning materials"
  on public.learning_materials for select to anon, authenticated using (true);

drop policy if exists "Public can read program budgets" on public.program_budgets;
create policy "Public can read program budgets"
  on public.program_budgets for select to anon, authenticated using (true);

grant select on public.products, public.learning_materials, public.program_budgets to anon, authenticated;

insert into public.products (id, name, price, image_position, description) values
  (1, 'Tenun Senja', 350000, '4% 50%', 'Nuansa jingga dengan motif geometris yang hangat.'),
  (2, 'Tenun Biru Pesisir', 385000, '25% 48%', 'Biru lembut dan benang keemasan untuk hari istimewa.'),
  (3, 'Tenun Mawar', 425000, '48% 45%', 'Merah muda dengan susunan motif yang kaya detail.'),
  (4, 'Tenun Hijau Daun', 375000, '64% 50%', 'Hijau dan detail motif tradisional yang bersahaja.'),
  (5, 'Tenun Pagi Lombok', 395000, '84% 50%', 'Warna hangat dengan motif terinspirasi suasana pagi di Lombok.'),
  (6, 'Tenun Ombak Biru', 410000, '100% 50%', 'Perpaduan biru laut dan pola berulang yang menenangkan.'),
  (7, 'Tenun Bunga Kecil', 360000, '12% 50%', 'Motif bunga mungil dengan warna lembut untuk berbagai suasana.'),
  (8, 'Tenun Langit Sore', 420000, '34% 50%', 'Perpaduan warna senja dan garis tradisional yang tegas.'),
  (9, 'Tenun Pucuk Pakis', 385000, '56% 50%', 'Motif terinspirasi pucuk pakis dengan nuansa alam.'),
  (10, 'Tenun Merah Rinjani', 435000, '76% 50%', 'Warna merah berani dengan susunan motif khas yang berkarakter.'),
  (11, 'Tenun Siger Ombak', 405000, '92% 50%', 'Pola geometris yang terinspirasi gerak ombak pesisir.'),
  (12, 'Tenun Pelangi Desa', 450000, '44% 50%', 'Ragam warna cerah dalam kain penuh cerita dan ketekunan.')
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  image_position = excluded.image_position,
  description = excluded.description;

insert into public.learning_materials (id, title, duration, steps) values
  (1, 'Mulai dari ponsel Anda', '5 menit', '["Hubungkan ponsel ke internet. Perbesar tulisan melalui pengaturan jika diperlukan.", "Buka situs Rantai Mawar. Kenali menu Koleksi, Ruang Belajar, dan Akun.", "Minta pendamping menemani latihan pertama. Anda boleh mengulang kapan saja."]'::jsonb),
  (2, 'Belanja tenun, langkah demi langkah', '7 menit', '["Buka Koleksi Tenun dan pilih kain yang ingin dilihat.", "Baca deskripsi dan harga. Tambahkan kain ke tas belanja.", "Periksa jumlah dan total sebelum membayar. Pada versi demo ini belum ada transaksi nyata."]'::jsonb),
  (3, 'Kenali pembayaran digital', '8 menit', '["Gunakan aplikasi bank atau dompet digital sendiri. Jangan berikan PIN dan OTP kepada siapa pun.", "Periksa nama penerima dan jumlah pembayaran sebelum menyetujui transaksi.", "Simpan bukti pembayaran. Jika ragu, berhenti dan minta pendamping memeriksa bersama."]'::jsonb),
  (4, 'Foto produk dengan ponsel', '6 menit', '["Letakkan kain di dekat jendela dengan cahaya alami.", "Gunakan latar polos. Ambil foto seluruh kain dan detail motifnya.", "Pastikan warna sesuai kain asli. Hindari filter yang mengubah warna."]'::jsonb)
on conflict (id) do update set
  title = excluded.title,
  duration = excluded.duration,
  steps = excluded.steps;

insert into public.program_budgets (id, description, amount) values
  (1, 'Pengembangan marketplace dan integrasi pembayaran', 12000000),
  (2, 'Pelatihan literasi digital dan pemasaran', 8000000),
  (3, 'Peralatan foto produk dan pendukung pelatihan', 6000000),
  (4, 'Pendampingan anggota dan operasional program', 7000000),
  (5, 'Dokumentasi, evaluasi, dan pelaporan', 4000000),
  (6, 'Koordinasi mitra dan kegiatan diseminasi', 3000000)
on conflict (id) do update set
  description = excluded.description,
  amount = excluded.amount;

select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products), true);
select setval(pg_get_serial_sequence('public.learning_materials', 'id'), (select max(id) from public.learning_materials), true);
