alter table public.products
  add column if not exists motif text not null default '',
  add column if not exists size text not null default '',
  add column if not exists material text not null default '',
  add column if not exists stock integer not null default 0,
  add column if not exists status text not null default 'pending',
  add column if not exists review_note text,
  add column if not exists updated_at timestamptz not null default now();

update public.products
set status = 'approved', stock = 20
where seller_id is null;

update public.products
set status = 'pending'
where seller_id is not null;

create index if not exists products_status_idx on public.products(status);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'products_status_check'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_status_check
      check (status in ('pending', 'approved', 'needs_revision'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'products_stock_check'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_stock_check check (stock >= 0);
  end if;
end;
$$;

create or replace function public.force_product_pending()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.status := 'pending';
  new.review_note := null;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists products_start_pending on public.products;
create trigger products_start_pending
before insert on public.products
for each row execute procedure public.force_product_pending();

alter table public.products enable row level security;
drop policy if exists "Public can read products" on public.products;
create policy "Public can read approved products"
  on public.products for select to anon, authenticated using (status = 'approved');
drop policy if exists "Sellers and admins can read their products" on public.products;
create policy "Sellers and admins can read their products"
  on public.products for select to authenticated
  using (seller_id = auth.uid() or public.is_admin());
drop policy if exists "Sellers can update their own products" on public.products;
create policy "Sellers can update their own unapproved products"
  on public.products for update to authenticated
  using (seller_id = auth.uid() and status in ('pending', 'needs_revision'))
  with check (seller_id = auth.uid() and status in ('pending', 'needs_revision'));
drop policy if exists "Admins can review products" on public.products;
create policy "Admins can review products"
  on public.products for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Sellers can delete their own products" on public.products;
create policy "Owners can delete unapproved products"
  on public.products for delete to authenticated
  using ((seller_id = auth.uid() and status in ('pending', 'needs_revision')) or public.is_admin());

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  buyer_name text not null,
  phone text not null,
  shipping_address text not null,
  payment_method text not null check (payment_method in ('QRIS', 'Transfer bank', 'Dompet digital')),
  payment_status text not null default 'waiting' check (payment_status in ('waiting', 'submitted', 'confirmed', 'rejected')),
  order_status text not null default 'awaiting_payment' check (order_status in ('awaiting_payment', 'checking', 'packaging', 'shipping', 'delivered', 'completed', 'cancelled')),
  subtotal bigint not null check (subtotal >= 0),
  shipping_cost bigint not null default 0 check (shipping_cost >= 0),
  total bigint not null check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  seller_id uuid references public.profiles(id) on delete set null,
  item_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  image_url text
);

create index if not exists orders_buyer_created_idx on public.orders(buyer_id, created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

grant select on public.orders, public.order_items to authenticated;
grant update (payment_status, order_status) on public.orders to authenticated;

drop policy if exists "Buyers and admins can read orders" on public.orders;
create policy "Buyers and admins can read orders"
  on public.orders for select to authenticated
  using (buyer_id = auth.uid() or public.is_admin());
drop policy if exists "Buyers can report payment" on public.orders;
create policy "Buyers can report payment"
  on public.orders for update to authenticated
  using (buyer_id = auth.uid() and order_status = 'awaiting_payment')
  with check (buyer_id = auth.uid() and order_status = 'awaiting_payment' and payment_status = 'submitted');
drop policy if exists "Admins can process orders" on public.orders;
create policy "Admins can process orders"
  on public.orders for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Order owners and admins can read order items" on public.order_items;
create policy "Order owners and admins can read order items"
  on public.order_items for select to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_id and (o.buyer_id = auth.uid() or public.is_admin())
    )
  );

create or replace function public.create_order(
  p_buyer_name text,
  p_phone text,
  p_shipping_address text,
  p_payment_method text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_product public.products%rowtype;
  v_item jsonb;
  v_product_id bigint;
  v_quantity integer;
  v_subtotal bigint := 0;
  v_buyer_id uuid := auth.uid();
begin
  if v_buyer_id is null then
    raise exception 'Silakan masuk untuk membuat pesanan.';
  end if;
  if length(trim(p_buyer_name)) < 2 or length(trim(p_buyer_name)) > 80 then
    raise exception 'Nama penerima harus 2-80 karakter.';
  end if;
  if length(trim(p_phone)) < 8 or length(trim(p_phone)) > 20 then
    raise exception 'Nomor telepon tidak valid.';
  end if;
  if length(trim(p_shipping_address)) < 10 or length(trim(p_shipping_address)) > 300 then
    raise exception 'Alamat pengiriman harus 10-300 karakter.';
  end if;
  if p_payment_method not in ('QRIS', 'Transfer bank', 'Dompet digital') then
    raise exception 'Metode pembayaran tidak valid.';
  end if;
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Pesanan tidak memiliki produk.';
  end if;

  for v_item in select value from jsonb_array_elements(p_items) as item(value) loop
    v_product_id := (v_item ->> 'product_id')::bigint;
    v_quantity := (v_item ->> 'quantity')::integer;
    if v_quantity < 1 then
      raise exception 'Jumlah produk tidak valid.';
    end if;

    select * into v_product
    from public.products
    where id = v_product_id and status = 'approved'
    for update;
    if not found then
      raise exception 'Salah satu produk sudah tidak tersedia.';
    end if;
    if v_product.stock < v_quantity then
      raise exception 'Stok % tidak mencukupi.', v_product.name;
    end if;

    update public.products set stock = stock - v_quantity, updated_at = now()
    where id = v_product.id;
    v_subtotal := v_subtotal + (v_product.price::bigint * v_quantity);
  end loop;

  insert into public.orders (
    buyer_id, buyer_name, phone, shipping_address, payment_method,
    payment_status, order_status, subtotal, shipping_cost, total
  ) values (
    v_buyer_id, trim(p_buyer_name), trim(p_phone), trim(p_shipping_address), p_payment_method,
    'waiting', 'awaiting_payment', v_subtotal, 0, v_subtotal
  ) returning id into v_order_id;

  for v_item in select value from jsonb_array_elements(p_items) as item(value) loop
    v_product_id := (v_item ->> 'product_id')::bigint;
    v_quantity := (v_item ->> 'quantity')::integer;
    select * into v_product from public.products where id = v_product_id;
    insert into public.order_items (order_id, product_id, seller_id, item_name, unit_price, quantity, image_url)
    values (v_order_id, v_product.id, v_product.seller_id, v_product.name, v_product.price, v_quantity, v_product.image_url);
  end loop;

  return v_order_id;
end;
$$;

grant execute on function public.create_order(text, text, text, text, jsonb) to authenticated;

create or replace function public.restore_stock_for_cancelled_order()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.order_status = 'cancelled' and old.order_status <> 'cancelled' then
    update public.products p
    set stock = p.stock + oi.quantity, updated_at = now()
    from public.order_items oi
    where oi.order_id = new.id and oi.product_id = p.id;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists restock_cancelled_order on public.orders;
create trigger restock_cancelled_order
before update on public.orders
for each row execute procedure public.restore_stock_for_cancelled_order();
